# Generated by Django 4.1.2 on 2023-01-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryclass',
            options={'verbose_name': 'Category Class', 'verbose_name_plural': 'Category Class'},
        ),
    ]
