# Generated by Django 4.1.2 on 2023-01-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_variationclass'),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductclass',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproductclass',
            name='size',
        ),
        migrations.AlterField(
            model_name='orderclass',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
        migrations.RemoveField(
            model_name='orderproductclass',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproductclass',
            name='variation',
            field=models.ManyToManyField(blank=True, to='app_store.variationclass'),
        ),
    ]
