# Generated by Django 4.1.2 on 2023-01-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_remove_orderproductclass_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclass',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('New', 'New'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
    ]
