# Generated by Django 4.1.2 on 2023-01-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_alter_orderclass_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclass',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('New', 'New')], default='New', max_length=50),
        ),
    ]
