# Generated by Django 4.1.2 on 2023-01-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userclass',
            options={'verbose_name': 'User Class', 'verbose_name_plural': 'User Class'},
        ),
    ]
