# Generated by Django 4.1.2 on 2023-01-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_variationclass'),
        ('app_carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemclass',
            name='variations',
            field=models.ManyToManyField(blank=True, to='app_store.variationclass'),
        ),
    ]
